#!/usr/bin/env python3
"""Generate dataclass API documentation from field metadata.

The dataclass field metadata is the source of truth for field-level
documentation. This script scans modules in ``src/teksi_hooks``, imports them,
finds dataclasses, and renders generated RST pages under
``docs/api/generated``.

Generated pages should not be edited manually.
"""

from __future__ import annotations

import argparse
import dataclasses
import importlib
import inspect
import sys
from pathlib import Path
from types import ModuleType
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = REPO_ROOT / "src"
PACKAGE_ROOT = SRC_ROOT / "teksi_hooks"
OUTPUT_DIR = REPO_ROOT / "docs" / "api" / "generated"

PACKAGE_NAME = "teksi_hooks"

HEADER = """.. This page is generated by scripts/generate_dataclass_docs.py.
   Do not edit manually.

"""


def module_name_for_file(
    path: Path,
) -> str:
    """Return the import module name for a Python file below teksi_hooks."""

    relative_path = path.relative_to(
        SRC_ROOT,
    )

    return ".".join(
        relative_path.with_suffix("").parts,
    )


def discover_module_names() -> list:
    """Discover importable modules in src/teksi_hooks.

    ``__init__.py`` is skipped. All other Python files below the package are
    considered. Modules that do not contain dataclasses are harmless and will
    simply not produce generated documentation pages.
    """

    module_names: list[str] = []

    for path in sorted(
        PACKAGE_ROOT.rglob("*.py"),
    ):
        if path.name == "__init__.py":
            continue

        module_names.append(
            module_name_for_file(
                path,
            )
        )

    return module_names


def import_module(
    module_name: str,
) -> ModuleType:
    """Import a module by name."""

    return importlib.import_module(
        module_name,
    )


def iter_local_dataclasses(
    module: ModuleType,
) -> list[type[Any]]:
    """Return dataclasses defined directly in a module."""

    classes: list[type[Any]] = []

    for _, obj in inspect.getmembers(
        module,
        inspect.isclass,
    ):
        if obj.__module__ != module.__name__:
            continue

        if dataclasses.is_dataclass(
            obj,
        ):
            classes.append(
                obj,
            )

    return classes


def render_type(
    annotation: Any,
) -> str:
    """Render a field annotation for RST output."""

    if isinstance(
        annotation,
        str,
    ):
        return annotation

    return getattr(
        annotation,
        "__name__",
        str(annotation),
    )


def render_doc(
    value: Any,
    *,
    language: str,
) -> str:
    """Render a metadata doc value.

    The current metadata convention is:

        metadata={"doc": "English text"}

    This helper also accepts a future translation-friendly shape:

        metadata={"doc": {"en": "...", "de": "..."}}
    """

    if isinstance(
        value,
        dict,
    ):
        return str(
            value.get(
                language,
                value.get(
                    "en",
                    "",
                ),
            )
            or ""
        )

    return str(
        value or "",
    )


def render_class(
    cls: type[Any],
    *,
    language: str,
) -> str:
    """Render one dataclass as RST."""

    title = cls.__name__

    bases = [base.__name__ for base in cls.__bases__ if base is not object]

    lines: list[str] = [
        title,
        "-" * len(title),
        "",
        f".. autoclass:: {cls.__module__}.{cls.__name__}",
        "   :members:",
        "",
    ]

    if bases:
        lines.extend(
            [
                f"Base class: ``{', '.join(bases)}``",
                "",
            ]
        )

    fields = dataclasses.fields(
        cls,
    )

    if not fields:
        return "\n".join(
            lines,
        )

    lines.extend(
        [
            "Fields",
            "~~~~~~",
            "",
        ]
    )

    for field in fields:
        field_type = render_type(
            field.type,
        )

        field_doc = render_doc(
            field.metadata.get(
                "doc",
                "",
            ),
            language=language,
        )

        lines.extend(
            [
                f"``{field.name}``",
                f"   Type: ``{field_type}``",
                "",
            ]
        )

        if field_doc:
            lines.extend(
                [
                    f"   {field_doc}",
                    "",
                ]
            )

    return "\n".join(
        lines,
    )


def module_title(
    module_name: str,
) -> str:
    """Return a readable title for a module page."""

    short_name = module_name.removeprefix(
        f"{PACKAGE_NAME}.",
    )

    return (
        short_name.replace(
            ".",
            " / ",
        )
        .replace(
            "_",
            " ",
        )
        .title()
    )


def page_name(
    module_name: str,
) -> str:
    """Return a stable generated page name for a module."""

    short_name = module_name.removeprefix(
        f"{PACKAGE_NAME}.",
    )

    return short_name.replace(
        ".",
        "_",
    )


def render_module_page(
    module_name: str,
    classes: list[type[Any]],
    *,
    language: str,
) -> str:
    """Render one generated RST page for a module."""

    title = module_title(
        module_name,
    )

    lines: list[str] = [
        HEADER,
        title,
        "=" * len(title),
        "",
        f".. automodule:: {module_name}",
        "",
    ]

    for cls in classes:
        lines.append(
            render_class(
                cls,
                language=language,
            )
        )
        lines.append(
            "",
        )

    return "\n".join(
        lines,
    )


def render_index(
    generated_pages: list[str],
) -> str:
    """Render the generated API index page."""

    lines: list[str] = [
        HEADER,
        "Generated API Reference",
        "=======================",
        "",
    ]

    if not generated_pages:
        lines.extend(
            [
                "No dataclass API pages were generated.",
                "",
            ]
        )
        return "\n".join(
            lines,
        )

    lines.extend(
        [
            ".. toctree::",
            "   :maxdepth: 2",
            "",
        ]
    )

    for generated_page in sorted(
        generated_pages,
    ):
        lines.append(
            f"   {generated_page}",
        )

    lines.append(
        "",
    )

    return "\n".join(
        lines,
    )


def generate(
    *,
    language: str,
) -> None:
    """Generate all dataclass documentation pages."""

    if str(SRC_ROOT) not in sys.path:
        sys.path.insert(
            0,
            str(SRC_ROOT),
        )

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    generated_pages: list[str] = []

    for module_name in discover_module_names():
        module = import_module(
            module_name,
        )

        classes = iter_local_dataclasses(
            module,
        )

        if not classes:
            continue

        output_name = page_name(
            module_name,
        )

        output_path = OUTPUT_DIR / f"{output_name}.rst"

        output_path.write_text(
            render_module_page(
                module_name,
                classes,
                language=language,
            ),
            encoding="utf-8",
        )

        generated_pages.append(
            output_name,
        )

        print(
            f"Wrote {output_path}",
        )

    index_path = OUTPUT_DIR / "index.rst"

    index_path.write_text(
        render_index(
            generated_pages,
        ),
        encoding="utf-8",
    )

    print(
        f"Wrote {index_path}",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=("Generate dataclass API documentation from field metadata."),
    )

    parser.add_argument(
        "--language",
        default="en",
        help=(
            "Documentation language key used when metadata['doc'] is a "
            "translation mapping. Defaults to 'en'."
        ),
    )

    return parser.parse_args()


def main() -> int:
    args = parse_args()

    generate(
        language=args.language,
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(
        main(),
    )
